# Generated by Django 4.1.2 on 2022-11-10 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_user_alter_todo_important'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='datecomplated',
            new_name='datecompleted',
        ),
    ]
