# Generated by Django 4.1.2 on 2022-11-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, unique=True)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
        migrations.RenameField(
            model_name='register',
            old_name='full_name',
            new_name='fullname',
        ),
    ]
